spring.application.name=citeria
server.port=8082
spring.profiles.active=dev
spring.web.locale=en
spring.datasource.url=jdbc:postgresql://localhost:5432/citeria_db
spring.datasource.username=vlad
spring.datasource.password=vlad
