spring.application.name=citeria

server.port=8082

# off Spring Security
spring.profiles.active=dev

spring.web.locale=en
spring.datasource.url=jdbc:postgresql://localhost:5432/citeria_db
spring.datasource.username=vlad
spring.datasource.password=vlad

# enable fail on unknown fields
spring.jackson.deserialization.fail-on-unknown-properties=true
